apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: install-sandbox-rhoam-operator
objects:
  - apiVersion: operators.coreos.com/v1alpha1
    kind: CatalogSource
    metadata:
      name: rhmi-operator
      namespace: ${RHOAM_NAMESPACE}
    spec:
      displayName: RHOAM Operators
      image: ${INDEX_IMAGE}
      sourceType: grpc
      updateStrategy:
        registryPoll:
          interval: 5m0s
  - apiVersion: operators.coreos.com/v1
    kind: OperatorGroup
    metadata:
      name: ${OPERATOR_GROUP_NAME}
      namespace: ${RHOAM_NAMESPACE}
    spec:
      targetNamespaces:
        - ${RHOAM_NAMESPACE}
  - apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: ${SUBSCRIPTION_NAME}
      namespace: ${RHOAM_NAMESPACE}
    spec:
      channel: ${CHANNEL}
      installPlanApproval: Automatic
      name: integreatly
      source: rhmi-operator
      sourceNamespace: ${RHOAM_NAMESPACE}
parameters:
  - name: RHOAM_NAMESPACE
    value: sandbox-rhoam-operator
  - name: INDEX_IMAGE
    value: quay.io/integreatly/managed-api-service-index:v1.12
  - name: OPERATOR_GROUP_NAME
    value: sandbox-rhoam-operator
  - name: SUBSCRIPTION_NAME
    value: managed-api-service
  - description: The name of the channel
    displayName: Channel Name
    name: CHANNEL
    value: alpha
---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: install-web-terminal-operator
objects:
  - apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: web-terminal
      namespace: ${WTO_NAMESPACE}
    spec:
      channel: fast
      installPlanApproval: Manual
      name: web-terminal
      source: redhat-operators
      sourceNamespace: openshift-marketplace
      startingCSV: web-terminal.v1.3.0
parameters:
  - name: WTO_NAMESPACE
    value: openshift-operators
---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: install-serverless-operator
objects:
  - apiVersion: operators.coreos.com/v1
    kind: OperatorGroup
    metadata:
      name: serverless-operator
      namespace: ${SERVERLESS_OPERATOR_NAMESPACE}
  - apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: serverless-operator-subscription
      namespace: ${SERVERLESS_OPERATOR_NAMESPACE}
    spec:
      channel: stable
      installPlanApproval: Automatic
      name: serverless-operator
      source: redhat-operators
      sourceNamespace: openshift-marketplace
      startingCSV: serverless-operator.v1.17.0
parameters:
  - name: SERVERLESS_OPERATOR_NAMESPACE
    value: serverless-operator